In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Device name {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is not available


Creating Tensors

In [ ]:
a = torch.empty(2, 3)
a

tensor([[1.6343e-38, 0.0000e+00, 1.6379e-38],
        [0.0000e+00, 1.6379e-38, 0.0000e+00]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.3441, 0.4904, 0.3376],
        [0.5921, 0.2383, 0.4188]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.arange(0,10, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Tensors Shape

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)  # Garbage value

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6067247193200274742, 3977586874590574896, 6499879764390130222]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32) #Have to declear the data tyoe

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

Data Type

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype = torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.float32)

In [ ]:
x.dtype

torch.float32

Mathmatical Operations

In [ ]:
X = torch.tensor([[1,2, 3], [4,5,6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
X+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
X*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [ ]:
X/2

tensor([0.5000, 1.0000, 1.5000, 2.0000])

In [ ]:
# Floor

X= X*100
X

tensor([[10000, 20000, 30000],
        [40000, 50000, 60000]])

In [ ]:
X//3

tensor([[ 3333,  6666, 10000],
        [13333, 16666, 20000]])

In [ ]:
X%2

tensor([[0, 0, 0],
        [0, 0, 0]])

Element Wise Operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [ ]:
b

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [ ]:
a+b

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [ ]:
a-b

tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])

In [ ]:
a*b

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [ ]:
a/b

tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [ ]:
a**b

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

In [ ]:
a%b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [ ]:
c = torch.tensor([-1, -2, -3, -4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
c = torch.tensor([1,2,3,4])

In [ ]:
torch.neg(c)

tensor([-1, -2, -3, -4])

In [ ]:
d = torch.tensor([1.2, 2.5, 3.5, 4.8])

In [ ]:
torch.round(d)

tensor([1., 2., 4., 5.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d, min= 1, max=3.4)

tensor([1.2000, 2.5000, 3.4000, 3.4000])

Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [ ]:
e

tensor([[0., 5., 1.],
        [8., 5., 4.]])

In [ ]:
torch.sum(e)

tensor(23.)

In [ ]:
# column wise sum
torch.sum(e, dim=0)

tensor([ 8., 10.,  5.])

In [ ]:
# row wise sum
torch.sum(e, dim=1)

tensor([ 6., 17.])

In [ ]:
torch.mean(e)

tensor(3.8333)

In [ ]:
torch.mean(e, dim=0)

tensor([4.0000, 5.0000, 2.5000])

In [ ]:
torch.mean(e, dim=1)

tensor([2.0000, 5.6667])

In [ ]:
torch.median(e)

tensor(4.)

In [ ]:
# max and min
torch.max(e)

tensor(8.)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
torch.prod(e)

tensor(0.)

In [ ]:
torch.std(e)

tensor(2.9269)

In [ ]:
# argmin, argmax
torch.argmax(e)  #returns the max value index

tensor(3)

In [ ]:
torch.argmin(e) # returns the min value index

tensor(0)

Matrix Operation

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
f

tensor([[3, 8, 1],
        [6, 0, 5]])

In [ ]:
g

tensor([[9, 9],
        [9, 0],
        [0, 2]])

In [ ]:
torch.matmul(f,g)

tensor([[99, 29],
        [54, 64]])

In [ ]:
# dot product
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [ ]:
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(2,3), low=0, high=10)
f

tensor([[9, 6, 4],
        [0, 5, 0]])

In [ ]:
g

tensor([[3, 1, 0],
        [8, 5, 3]])

In [ ]:
f.shape

torch.Size([2, 3])

In [ ]:
# transpose
f = torch.transpose(f, 0,1)

In [ ]:
f.shape

torch.Size([3, 2])

In [ ]:
torch.matmul(g,f)

tensor([[ 33,   5],
        [114,  25]])

In [ ]:
# determinant
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(h)

tensor(96.0000)

In [ ]:
torch.inverse(h)

tensor([[-1.1176e-08, -3.7500e-01,  2.5000e-01],
        [ 2.5000e-01,  1.2500e-01, -2.5000e-01],
        [ 1.4901e-08,  1.6667e-01,  4.9671e-09]])

Comparison Operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

In [ ]:
i

tensor([[6, 6, 9],
        [2, 0, 8]])

In [ ]:
j

tensor([[7, 5, 8],
        [0, 4, 3]])

In [ ]:
# greater than
i > j      # compare every element

tensor([[False,  True,  True],
        [ True, False,  True]])

In [ ]:
# less than
i < j

tensor([[ True, False, False],
        [False,  True, False]])

In [ ]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to

i != j

tensor([[True, True, True],
        [True, True, True]])

Special Function

In [ ]:
k = torch.tensor([0.001, 20, 30])
k

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

In [ ]:
torch.log(k)   # ln()

tensor([-6.9078,  2.9957,  3.4012])

In [ ]:
# exp
torch.exp(k)

tensor([1.0010e+00, 4.8517e+08, 1.0686e+13])

In [ ]:
torch.sqrt(k)

tensor([0.0316, 4.4721, 5.4772])

In [ ]:
#sgmoid
torch.sigmoid(k)

tensor([0.5002, 1.0000, 1.0000])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([9.3666e-14, 4.5398e-05, 9.9995e-01])

In [ ]:
torch.relu(k)

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

In [ ]:
torch.nn.functional.leaky_relu(k, negative_slope=0.01)

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

Inplace Operations

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a + 5 # not inplace waste space
b

tensor([6, 7, 8])

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [ ]:
m

tensor([[0.5004, 0.8864, 0.5414],
        [0.9018, 0.5289, 0.4512]])

In [ ]:
n

tensor([[0.6071, 0.8812, 0.1659],
        [0.0803, 0.6189, 0.1761]])

In [ ]:
m.add_(n) # inplce, here the m is changed now

tensor([[1.1074, 1.7676, 0.7074],
        [0.9821, 1.1478, 0.6273]])

In [ ]:
m

tensor([[1.1074, 1.7676, 0.7074],
        [0.9821, 1.1478, 0.6273]])

In [ ]:
torch.relu_(m)

tensor([[1.1074, 1.7676, 0.7074],
        [0.9821, 1.1478, 0.6273]])

Copy A tensor

In [ ]:
a  = torch.tensor([1,2,3,4,5])
a

tensor([1, 2, 3, 4, 5])

In [ ]:
# deep copy
b = a

In [ ]:
b

tensor([1, 2, 3, 4, 5])

In [ ]:
b[2] = 30
b

tensor([ 1,  2, 30,  4,  5])

In [ ]:
a  # a has also changed autometically

tensor([ 1,  2, 30,  4,  5])

In [ ]:
aa = torch.tensor([1,2,3,4,5])
aa

tensor([1, 2, 3, 4, 5])

In [ ]:
# shallow copy
bb = aa.clone()
bb

tensor([1, 2, 3, 4, 5])

In [ ]:
aa  # aa has not changed

tensor([1, 2, 3, 4, 5])